###
POST http://localhost:8080/api/client/auth/signout

###
POST http://localhost:8080/api/client/auth/signup
Content-Type: application/json

{
  "name": "Gianni",
  "surname": "Di costanzo",
  "email": "gianni.dicostanzo@gmail.com",
  "password": "SonoGianni007",
  "telephoneNumber": "3356785378"
}

###
POST http://localhost:8080/api/client/auth/signin
Content-Type: application/json

{
  "email": "gianni.dicostanzo@gmail.com",
  "password": "SonoGianni007"
}

###
POST http://localhost:8080/api/client/isRegisteredTo/1
#false

###
POST http://localhost:8080/api/client/registerToCampaign/1

###
POST http://localhost:8080/api/client/isRegisteredTo/1
#true

###
POST http://localhost:8080/api/client/registerToCampaign/1

###
GET http://localhost:8080/api/customerCard/getCards
#1 card
